services:
  api:
    image: ghcr.io/neojelll/url-shortener-api:0.1.11
    ports:
      - "8000:8000"
    environment:
      CACHE_TTL: "3600"
      CACHE_HOST: "redis"
      CACHE_PORT: "6379"
      BROKER_HOST: "kafka"
      BROKER_PORT: "9092"
      DB_USERNAME: "neojelll"
      DB_HOST: "5432"
      DB_PORT: "postgres"
      DB_NAME: "mydatabase"
      DB_PASSWORD: "123"
    depends_on:
      - redis
      - postgres
      - kafka
  
  expiration-manager:
    image: ghcr.io/neojelll/url-shortener-expiration-manager:0.1.14

  kafka:
    image: bashj79/kafka-kraft:latest

  redis:
    image: redis:latest

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "neojelll"
      POSTGRES_DB: "mydatabase"
      POSTGRES_PASSWORD: "123"
