[tool.poetry]
name = "architecture"
version = "0.1.0"
authors = ["neojelll <timofejmitusin60892@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.12"
diagrams = "^0.24.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
