name: Python package

on:
  push:
    branches:
      - '**'

jobs:
  integration:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.12"

    - name: Check Project name
      run: |
        export PROJECT_NAME=$(git log -1 --name-only --pretty=format: | awk -F'/' '{print $1}' | sort -u | head -n 1)
        echo $PROJECT_NAME
        echo "PROJECT_NAME=${PROJECT_NAME}" >> $GITHUB_ENV
        if [[ $PROJECT_NAME == .* || $PROJECT_NAME == *.log || $PROJECT_NAME == README.md ]]; then
          echo "Warning: PROJECT_NAME ($PROJECT_NAME) does not fit, further steps will be skipped."
          echo "SKIP_REMAINING_STEPS=true" >> $GITHUB_ENV
        fi

    - name: Install Poetry
      if: env.SKIP_REMAINING_STEPS != 'true'
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      if: env.SKIP_REMAINING_STEPS != 'true'
      run: |
        cd ${{ env.PROJECT_NAME }}
        poetry install

    - name: Lint with Ruff
      if: env.SKIP_REMAINING_STEPS != 'true'
      run: |
        cd ${{ env.PROJECT_NAME }}
        poetry run ruff check ${{ env.PROJECT_NAME }}
        poetry run ruff format --check ${{ env.PROJECT_NAME }} 

    - name: Test with pytest
      if: env.SKIP_REMAINING_STEPS != 'true'
      run: |
        cd ${{ env.PROJECT_NAME }}
        poetry run pytest tests
